# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "k3ilona/publisher-slack-bot"
  pullPolicy: IfNotPresent # Дозволяє замінити образ за замовчуванням
  tag: 1.0.0-dev-51d4a0e-1706565759 # echo $(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
  os: linux
  arch: amd64
  parameter: go
secret:
  - name: "ibot"
    env: "SLACK_AUTH_TOKEN"
    key: "token"
  - name: "ibot"
    env: "SLACK_CHANNEL_ID"
    key: "channel-id"
  - name: "ibot"
    env: "SLACK_APP_TOKEN"
    key: "appToken"
securityContext:
  privileged: true
