# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "k3ilona/publisher-slack-bot"
  pullPolicy: IfNotPresent # Дозволяє замінити образ за замовчуванням
  tag: 1.0.0-f6c0673       # echo $(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
  os: linux
  arch: amd64
  parameter: go

secret:
  secret1:  
    name: "ibot"
    env: "SLACK_AUTH_TOKEN"
    key: "auth-token"
  secret2:
    name: "ibot-channel"
    env: "SLACK_CHANNEL_ID"
    key: "channel-id"
  secret3:
    name: "ibot-app"
    env: "SLACK_APP_TOKEN"
    key: "app-token"
securityContext:
  privileged: true

