name: DEV-CI

on: 
  push:
    branches:
      - dev

jobs:
  ci:
    name: DEV-CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: writepermissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run test
      run: make test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build_Push
      env:
        APP: "ibot"
        REGESTRY: "ghcr.io/k3ilona"
      run: make image push
    - name: Clean
      run: make clean
