name: DEV-CI

on: 
  push:
    branches:
      - dev

jobs:
  ci:
    name: DEV-CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run test
      run: make test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build_Push
      env:
        APP: "ibot"
        REGESTRY: "ghcr.io/k3ilona"
      run: make image push
    - name: Clean
      run: make clean
      
  helm:
    name: DEV-HELM
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Define tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Define version
      run: echo "VERSION=$TAG-${{ github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: |
          yq -i '.image.tag = strenv(VERSION)' helm/values.yaml 
          yq -i '.appVersion = strenv(TAG)' helm/Chart.yaml

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push -f

  qa:
    name: DEV-QA
    needs: helm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        email: github-actions@github.com
        name: github-actions
        commit_message: "Update version $VERSION"
        target_branch: qa
        files: .
        access_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
