name: DEV-CI

on: 
  push:
    branches:
      - dev

jobs:
  ci:
    name: DEV-CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run test
      run: make test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push to GitHub Container Registry
      env:
        APP: "ibot"
        REGESTRY: "ghcr.io/k3ilona"
      run: make image push
    - name: Clean
      run: make clean
      
  helm:
    name: DEV-HELM
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Define tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Define version
      run: echo "VERSION=$TAG-${{ github.ref_name }}-$(git rev-parse --short HEAD)-$(date +%s)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: |
          yq -i '.image.tag = strenv(VERSION)' helm/values.yaml 
          yq -i '.appVersion = strenv(TAG)' helm/Chart.yaml

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push -f

  push:
    name: DEV-QA
    needs: helm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Merge branch
      run: |
        git checkout qa
        git merge dev --no-edit  # replace source-branch and target-branch with your branch names
        git push
